---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utility
  namespace: utility
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded