apiVersion: v1
kind: ConfigMap
metadata:
  name: cord-infra-initializer
  namespace: utility
data:
  config: |
    containers:
    - name: cord-infra-sidecar
      image: {{ .Values.images.infra_helper.repository }}:{{ .Values.images.infra_helper.tag }}
      env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      imagePullPolicy: IfNotPresent
