apiVersion: apps/v1beta1
kind: Deployment
metadata:
  initializers:
    pending: []
  labels:
    app: cord-infra-initializer
  name: cord-infra-initializer
  namespace: utility
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cord-infra-initializer
      name: cord-infra-initializer
    spec:
      serviceAccount: utility
      serviceAccountName: utility
      containers:
      - name: cord-infra-initializer
        image: gopinatht/cord-infra-initializer
        imagePullPolicy: IfNotPresent
        args:
        - "-initializer-name=cord-infra.initializer.onf.io"
        - "-configmap=cord-infra-initializer"
   
